### ISSUE TITLE
Bug: a group delete but not remove from mobile client

### ISSUE THREAD

**Issue by aschenmaker** [Privoce/vocechat-client#21] opened 2022-11-29 03:35 UTC
When I removed a group from web client, but the group still stay in group member's IOS message list.

## How to reproduce

1. Delete a group from web page.
2. From the view of group members' iOS client, can see the delete group still remained.

Maybe cache not refresh. Because group has been already deleted, I can't leave from ios client. And there has no options let me delete the group message.

**Comment by shuotwang** [comment] 2022-11-29 19:41
I've tested it and the group is deleted as it should be. We are looking into it and trying to reproduce this issue. Our temporary modification might be: delete channel locally if the channel has been deleted in backend, to solve ' Because group has been already deleted, I can't leave from iOS client' issue.  Also, we are planning to add warning popups if a user is viewing a channel (and its child pages) that is being deleted by others. Further updates might be ready in a week or two, depending on our plan.

**Comment by shuotwang** [comment] 2022-11-30 01:28
Just realized the reason of this issue. Change in progress.

**Comment by shuotwang** [comment] 2022-12-06 05:22
Issue has been solved. New versions are under review, and will be released very soon.

**Closed by shuotwang** 2022-12-06 05:22 UTC
